---
name: NetBird-Client
version: 1.16.0
slug: netbird_client
description: Connect your devices into a single secure private WireGuard®-based mesh network with SSO/MFA and simple access controls.
url: https://github.com/dannymate/hassio-addons
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
  - config:rw
options:
  ADMIN_URL: ""
  MANAGEMENT_URL: "" 
  SETUP_KEY: ""
  HOSTNAME: ""
schema:
  ADMIN_URL: str
  MANAGEMENT_URL: str
  SETUP_KEY: str
  HOSTNAME: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
